version: '3.4'

services:
  datarecoverymodule:
    image: datarecoverymodule
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8082:8082
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./bin/www"]
